python receive_logs_direct.py warning error > logs_from_rabbit.log
